### ISSUE TITLE
No module named 'nb_srv6_manager_pb2_grpc' - Docker

### ISSUE THREAD

**Issue by rafaelhribeiro** [netgroup/rose-srv6-control-plane#86]
I am getting the following ModuleNotFoundError exception when I try to run the controller in a Docker container:

        import nb_srv6_manager_pb2_grpc

        ModuleNotFoundError: No module named 'nb_srv6_manager_pb2_grpc'

I have built the container using the following command: 

    docker build --target controller -t rose-srv6-controller:latest . --no-cache

I just opened the container and typed `controller`, then this exception was thrown. The full output is shown below: 

    Traceback (most recent call last):

    File "/usr/local/bin/controller", line 11, in <module>

    load_entry_point('rose-srv6-control-plane-controller==0.0.1', 'console_scripts', 'controller')()

    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point

    return ep.load()

    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load

    return self.resolve()

    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

    File "/usr/local/lib/python3.7/dist-packages/rose_srv6_control_plane_controller-0.0.1-py3.7.egg/controller/controller_cli.py", line 46, in <module>

    from controller.nb_grpc_server import grpc_server

    File "/usr/local/lib/python3.7/dist-packages/rose_srv6_control_plane_controller-0.0.1-py3.7.egg/controller/nb_grpc_server/grpc_server.py", line 45, in <module>

    import nb_srv6_manager_pb2_grpc

    ModuleNotFoundError: No module named 'nb_srv6_manager_pb2_grpc'

**Comment by cscarpitta** [comment]
Hi, I'm going to merge a PR that should fix your problem.
Please, `pull` the changes and try to rebuild the container.

Regards,
Carmine
