### ISSUE TITLE
errors: ModuleNotFoundError: No module named 'nb_srv6_manager_pb2_grpc

### ISSUE THREAD

**Issue by causimmi** [netgroup/rose-srv6-control-plane#89]
#` controller --env-file .env `

```
Traceback (most recent call last):
  File "/home/rose/.envs/controller-venv/bin/controller", line 11, in <module>
    load_entry_point('rose-srv6-control-plane-controller==0.0.1', 'console_scripts', 'controller')()
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/rose_srv6_control_plane_controller-0.0.1-py3.8.egg/controller/controller_cli.py", line 46, in <module>
    from controller.nb_grpc_server import grpc_server
  File "/home/rose/.envs/controller-venv/lib/python3.8/site-packages/rose_srv6_control_plane_controller-0.0.1-py3.8.egg/controller/nb_grpc_server/grpc_server.py", line 45, in <module>
    import nb_srv6_manager_pb2_grpc
ModuleNotFoundError: **_No module named 'nb_srv6_manager_pb2_grpc_**
```

**Comment by StefanoSalsano** [comment]
may be this is related to https://github.com/netgroup/rose-vm/issues/38
